import { faker } from "@faker-js/faker"

const email = "joko@mailinator.com"
const pwd = "@Joko123"
const firstName = faker.name.firstName();
const lastName = faker.name.lastName();
const fakeEmail = `${firstName}@mailinator.com`;
const password = faker.internet.password();
const fullname = `${firstName} ${lastName}`
const loginUrl = "https://magento.softwaretestingboard.com/customer/account/login/referer/aHR0cHM6Ly9tYWdlbnRvLnNvZnR3YXJldGVzdGluZ2JvYXJkLmNvbS8%2C/"

describe('Automation UI Testing Using Cypress', () => {
   it('Register Success Using Valid Data', () => {
     cy.visit('https://magento.softwaretestingboard.com/')
     cy.wait(1000)
     cy.get('.panel > .header > :nth-child(3) > a').click()
     cy.wait(2000)
     cy.get('#firstname').type(firstName)
     cy.wait(2000)
     cy.get('#lastname').type(lastName)
     cy.wait(2000)
     cy.get('#email_address').type(fakeEmail)
     cy.wait(2000)
     cy.get('#password').type(password)
     cy.wait(2000)
     cy.get('#password-confirmation').type(password)
     cy.wait(2000)
     cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
   })
  // it('Register Failed Using Already Data', () => {
  //   cy.visit('https://magento.softwaretestingboard.com/')
  //   cy.wait(1000)
  //   cy.get('.panel > .header > :nth-child(3) > a').click()
  //   cy.wait(2000)
  //   cy.get('#firstname').type(firstName)
  //   cy.wait(2000)
  //   cy.get('#lastname').type(lastName)
  //   cy.wait(2000)
  //   cy.get('#email_address').type(fakeEmail)
  //   cy.wait(2000)
  //   cy.get('#password').type(password)
  //   cy.wait(2000)
  //   cy.get('#password-confirmation').type(password)
  //   cy.wait(2000)
  //   cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
  //   cy.wait(2000)
  //   cy.get('.message-error').contains('There is already an account with this email address. If you are sure that it is your email address, click here to get your password and access your account.')
  //   cy.wait(2000)
  // })
  // it('Register Failed with Empty Fisrtname', () => {
  //   cy.visit('https://magento.softwaretestingboard.com/')
  //   cy.wait(1000)
  //   cy.get('.panel > .header > :nth-child(3) > a').click()
  //   cy.wait(2000)
  //   cy.get('#lastname').type(`${faker.name.lastName()}`)
  //   cy.wait(2000)
  //   cy.get('#email_address').type(`${faker.name.firstName()}@mailinator.com`)
  //   cy.wait(2000)
  //   cy.get('#password').type(`${faker.internet.password()}`)
  //   cy.wait(2000)
  //   cy.get('#password-confirmation').type(`${faker.internet.password()}`)
  //   cy.wait(2000)
  //   cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
  //   cy.wait(2000)
  //   cy.get('#firstname-error').contains('This is a required field.')
  // })
  // it('Register Failed with Empty Lastname', () => {
  //   cy.visit('https://magento.softwaretestingboard.com/')
  //   cy.wait(1000)
  //   cy.get('.panel > .header > :nth-child(3) > a').click()
  //   cy.wait(2000)
  //   cy.get('#firstname').type(`${faker.name.firstName()}`)
  //   cy.wait(2000)
  //   cy.get('#email_address').type(`${faker.name.firstName()}@mailinator.com`)
  //   cy.wait(2000)
  //   cy.get('#password').type(`${faker.internet.password()}`)
  //   cy.wait(2000)
  //   cy.get('#password-confirmation').type(`${faker.internet.password()}`)
  //   cy.wait(2000)
  //   cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
  //   cy.wait(2000)
  //   cy.get('#lastname-error').contains('This is a required field.')
  // })
  // it('Register Failed with Empty Email Address', () => {
  //   cy.visit('https://magento.softwaretestingboard.com/')
  //   cy.wait(1000)
  //   cy.get('.panel > .header > :nth-child(3) > a').click()
  //   cy.wait(2000)
  //   cy.get('#firstname').type(`${faker.name.firstName()}`)
  //   cy.wait(2000)
  //   cy.get('#lastname').type(`${faker.name.lastName()}`)
  //   cy.wait(2000)
  //   cy.get('#password').type(`${faker.internet.password()}`)
  //   cy.wait(2000)
  //   cy.get('#password-confirmation').type(`${faker.internet.password()}`)
  //   cy.wait(2000)
  //   cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
  //   cy.wait(2000)
  //   cy.get('#email_address-error').contains('This is a required field.')
  // })
  // it('Register Failed with Empty Password', () => {
  //   cy.visit('https://magento.softwaretestingboard.com/')
  //   cy.wait(1000)
  //   cy.get('.panel > .header > :nth-child(3) > a').click()
  //   cy.wait(2000)
  //   cy.get('#firstname').type(`${faker.name.firstName()}`)
  //   cy.wait(2000)
  //   cy.get('#lastname').type(`${faker.name.lastName()}`)
  //   cy.wait(2000)
  //   cy.get('#email_address').type(`${faker.name.firstName()}@mailinator.com`)
  //   cy.wait(2000)
  //   cy.get('#password-confirmation').type(`${faker.internet.password()}`)
  //   cy.wait(2000)
  //   cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
  //   cy.wait(2000)
  //   cy.get('#password-error').contains('This is a required field.')
  // })
  // it('Register Failed with Empty Confirm Password', () => {
  //   cy.visit('https://magento.softwaretestingboard.com/')
  //   cy.wait(1000)
  //   cy.get('.panel > .header > :nth-child(3) > a').click()
  //   cy.wait(2000)
  //   cy.get('#firstname').type(`${faker.name.firstName()}`)
  //   cy.wait(2000)
  //   cy.get('#lastname').type(`${faker.name.lastName()}`)
  //   cy.wait(2000)
  //   cy.get('#email_address').type(`${faker.name.firstName()}@mailinator.com`)
  //   cy.wait(2000)
  //   cy.get('#password').type(`${faker.internet.password()}`)
  //   cy.wait(2000)
  //   cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
  //   cy.wait(2000)
  //   cy.get('#password-confirmation-error').contains('This is a required field.')
  // })

  // it('Login Success with Valid Data', () => {
  //   cy.visit(loginUrl)
  //   cy.wait(1000)
  //   cy.get('#email').type(fakeEmail)
  //   cy.wait(2000)
  //   cy.get('#pass').type(password)
  //   cy.wait(2000)
  //   cy.get('#send2').click()
  //   cy.wait(2000)
  //   cy.get(':nth-child(2) > .greet > .logged-in').contains(`Welcome, ${fullname}`)
  //   cy.log(fullname);
  // })
  it('Login Failed with Invalid Email', () => {
    cy.visit(loginUrl)
    cy.wait(1000)
    cy.get('#email').type(`${faker.name.firstName()}@mailinator.com`)
    cy.wait(2000)
    cy.get('#pass').type(password)
    cy.wait(2000)
    cy.get('#send2').click()
    cy.wait(2000)
    cy.get('.message-error').contains('The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.')
  })
  it('Login Failed with Invalid Password', () => {
    cy.visit(loginUrl)
    cy.wait(1000)
    cy.get('#email').type(fakeEmail)
    cy.wait(2000)
    cy.get('#pass').type(`${faker.internet.password()}`)
    cy.wait(2000)
    cy.get('#send2').click()
    cy.wait(2000)
    cy.get('.message-error').contains('The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.')
  })
  it('Login Failed without Input Email', () => {
    cy.visit(loginUrl)
    cy.wait(1000)
    cy.get('#pass').type(password)
    cy.wait(2000)
    cy.get('#send2').click()
    cy.wait(2000)
    cy.get('#email-error').contains('This is a required field.')
  })
  it('Login Failed without Input Password', () => {
    cy.visit(loginUrl)
    cy.wait(1000)
    cy.get('#email').type(fakeEmail)
    cy.wait(2000)
    cy.get('#send2').click()
    cy.wait(2000)
    cy.get('#pass-error').contains('This is a required field.')
  })
  it('Login Failed without Input Email & Password', () => {
    cy.visit(loginUrl)
    cy.wait(1000)
    cy.get('#send2').click()
    cy.wait(1000)
    cy.get('#email-error').contains('This is a required field.')
    cy.wait(1000)
    cy.get('#pass-error').contains('This is a required field.')
  })
})